### ISSUE TITLE
Broken "Edit post on GitHub" links

### ISSUE THREAD

**Issue by igorskyflyer** [tylerwray/me#21]
Hey man, I just saw your Astro site in the Issues section of their repository and as every curious developer I had to take a look. 😁 Nice site indeed but I noticed that the links for the `"Edit post on GitHub"` are broken due to a trailing slash of the post's URL.

<br>

<p align="center">
<img src="https://user-images.githubusercontent.com/20957750/206320080-19c478be-a4e1-47d4-a458-b23cc4a7ac8c.png">
</p>

I will be posting a PR for this issue. 😊

> Sidenote: the `"Discuss on Twitter"` is broken as well and it contains a `TODO` comment, i.e. https:\/\/mobile.twitter.com/search?q=`%2FTODO-blogPostUrl`.

**Comment by tylerwray** [comment]
I missed this a while back. Thanks for flagging @igorskyflyer! I'm fixing these today.
